### PR TITLE
Wake Controls

### PR DESCRIPTION
**Pull request by javelinanddart**
S2S, Sweep2Wake Leniency, Sweep2Wake Timeout, DT2W, DT2S

### CODE REVIEW

**Comment by javelinanddart** [comment]
Testing last commit still

**Comment by NoSpamDan** [comment]
This one?
https://github.com/javelinanddart/kernel_samsung_msm8660/commit/88910ccf8073f1a69aa0034d77e7287334b44b23

**Comment by javelinanddart** [comment]
Yes

**Comment by NoSpamDan** [comment]
Does that affect StatusBar DT2S?

**Comment by javelinanddart** [comment]
No
That's not even related to kernel, that's framework stuff

**Comment by NoSpamDan** [comment]
I didn't dig into it... thx

**Comment by javelinanddart** [comment]
It does work BTW. Can be reopened.

**Comment by NoSpamDan** [comment]
Great, thanks

Dan

**Comment by javelinanddart** [comment]
Merge pls lol

**Comment by NoSpamDan** [comment]
Thanks, Paul. Merged.

Will test now

**Comment by javelinanddart** [comment]
NP, just happy it will be shipped and used :)

**Pull request merged**
